import sqlite3
import requests



DicoLiensCartes={
    'Ambassade-Ambassadeur':'https://iili.io/dugrvrN.png',
    'Ambassade-Conseiller culturel':'https://iili.io/dugreBR.png',
    'Ambassade-Conseiller scientifique':'https://iili.io/dugrgkX.png',
    'Ambassade-Correspondant informatique':'https://iili.io/dugrrpn.png',
    'Ambassade-Secretaire':'https://iili.io/dugr6Is.png',
    'Ambassade-attache de defense':'https://iili.io/dugrk1p.png',
    'Ambassade-conseiller economique':'https://iili.io/dugrNLv.png',
    'Avion-Agent de vente':'https://iili.io/dugrU7t.png',
    'Avion-Co pilote':'https://iili.io/dugrPhG.png',
    'Avion-Hotesse de l air':'https://iili.io/dugriQf.png',
    'Avion-Passager':'https://iili.io/dugrQEl.png',
    'Avion-Pilote':'https://iili.io/dugrZ42.png',
    'Avion-Preparateur des plateaux repas':'https://iili.io/dugrD2S.png',
    'Avion-Stewart':'https://iili.io/dugrbY7.png',
    'Banque-Analyste financier':'https://iili.io/dugrmv9.png',
    'Banque-Client':'https://iili.io/dug49Tu.png',
    'Banque-Client dans le rouge':'https://iili.io/dugrppe.png',
    'Banque-Conseiller':'https://iili.io/dug4Hhb.png',
    'Banque-Directeur':'https://iili.io/dug4JQj.png',
    'Banque-Guichetier':'https://iili.io/dug42Cx.png',
    'Banque-Trade':'https://iili.io/dug43EQ.png',
    'Base militaire-Assistant administratif':'https://iili.io/dug4f3B.png',
    'Base militaire-Chauffeur Poids Lourd':'https://iili.io/dug4qYP.png',
    'Base militaire-Colonel':'https://iili.io/dug4Bv1.png',
    'Base militaire-Infirmiere':'https://iili.io/dug4CyF.png',
    'Base militaire-Maitre chien':'https://iili.io/dug4oTg.png',
    'Base militaire-Operateur reseau':'https://iili.io/dug4xja.png',
    'Base militaire-Pilote d avion':'https://iili.io/dug4zZJ.png',
    'Bateau pirate-Capitaine':'https://iili.io/dug4TCv.png',
    'Bateau pirate-Chef de la carte au tresor':'https://iili.io/dug4A4p.png',
    'Bateau pirate-Cuisinier':'https://iili.io/dug453N.png',
    'Bateau pirate-Gerant des voiles':'https://iili.io/dug47aI.png',
    'Bateau pirate-Maitre Artilleur':'https://iili.io/dug4Yvt.png',
    'Bateau pirate-Matelot':'https://iili.io/dug4ayX.png',
    'Bateau pirate-Prisonnier':'https://iili.io/dug4lun.png',
    'Boite de nuit-Barman':'https://iili.io/dug40js.png',
    'Boite de nuit-Client':'https://iili.io/dug4Gnf.png',
    'Boite de nuit-Client Bourre':'https://iili.io/dug41ZG.png',
    'Boite de nuit-DJ':'https://iili.io/dug4XF2.png',
    'Boite de nuit-Danseur':'https://iili.io/dug4MG4.png',
    'Boite de nuit-Responsable Lumieres':'https://iili.io/dug4haS.png',
    'Boite de nuit-Videur':'https://iili.io/dug4j87.png',
    'Carnaval-Deguise en Mousquetaire':'https://iili.io/dug4Oue.png',
    'Carnaval-Deguise en Obelix':'https://iili.io/dug4ewu.png',
    'Carnaval-Deguise en Pirate':'https://iili.io/dug4kZb.png',
    'Carnaval-Deguise en SUper Heros':'https://iili.io/dug48nj.png',
    'Carnaval-Deguise en loup':'https://iili.io/dug4N99.png',
    'Carnaval-Deguise en table basse':'https://iili.io/dug4SMx.png',
    'Carnaval-Deguisement oublie':'https://iili.io/dug4rFV.png',
    'Casino-Banquier':'https://iili.io/dug44cB.png',
    'Casino-Croupier':'https://iili.io/dug4i91.png',
    'Casino-Directeur':'https://iili.io/dug4sAF.png',
    'Casino-Joueur gagnant':'https://iili.io/dug4Lwg.png',
    'Casino-Joueur perdant':'https://iili.io/dug4toJ.png',
    'Casino-Responsable securite':'https://iili.io/dug4DMv.png',
    'Casino-Tricheur':'https://iili.io/dug4bPR.png',
    'Centre de Thalasso-Client':'https://iili.io/dug4pFp.png',
    'Centre de Thalasso-Dieteticien':'https://iili.io/dug4ycN.png',
    'Centre de Thalasso-Estheticien':'https://iili.io/dug69SI.png',
    'Centre de Thalasso-Kinesitherapeute':'https://iili.io/dug6J9t.png',
    'Centre de Thalasso-Maitre nageur':'https://iili.io/dug63ts.png',
    'Centre de Thalasso-Masseur':'https://iili.io/dug6CKl.png',
    'Centre de Thalasso-Receptionniste':'https://iili.io/dug6zH7.png',
    'Cirque-Acrobate':'https://iili.io/dug6IR9.png',
    'Cirque-Cavalier':'https://iili.io/dug6uDu.png',
    'Cirque-Clown':'https://iili.io/dug67ix.png',
    'Cirque-Dompteur de tigre':'https://iili.io/dug6lUB.png',
    'Cirque-Jongleur':'https://iili.io/dug6GOF.png',
    'Cirque-Magicien':'https://iili.io/dug6XWJ.png',
    'Cirque-Responsable billeterie':'https://iili.io/dug6wfR.png',
    'Croisades-Archer':'https://iili.io/dug6OUN.png',
    'Croisades-Chevalier':'https://iili.io/dug6vRt.png',
    'Croisades-Ecuyer':'https://iili.io/dug6gxs.png',
    'Croisades-Garde':'https://iili.io/dug64sf.png',
    'Croisades-Paysan':'https://iili.io/dug6sg2.png',
    'Croisades-Prêtre':'https://iili.io/dug6Z57.png',
    'Croisades-Seigneur':'https://iili.io/dug6Dbe.png',
    'Ecole-Agent d entretient':'https://iili.io/dug6ysj.png',
    'Ecole-Directeur':'https://iili.io/dugPJ0Q.png',
    'Ecole-Eleve':'https://iili.io/dugP3dB.png',
    'Ecole-Infirmiere':'https://iili.io/dugPKe1.png',
    'Ecole-Professeur':'https://iili.io/dugPnLJ.png',
    'Ecole-Remplacant':'https://iili.io/dugPIgp.png',
    'Ecole-Responsable cantine':'https://iili.io/dugPA7I.png',
    'Fete d entreprise-Alternant':'https://iili.io/dugPRet.png',
    'Fete d entreprise-Apprenti':'https://iili.io/dugPcLG.png',
    'Fete d entreprise-Assistant administratif':'https://iili.io/dugP0Bf.png',
    'Fete d entreprise-PDG':'https://iili.io/dugPErl.png',
    'Fete d entreprise-Salarie licencie':'https://iili.io/durFiZb.png',
    'Fete d entreprise-Scretaire':'https://iili.io/dugPXp9.png',
    'Fete d entreprise-Stagiaire':'https://iili.io/dugPwhu.png',
    'Garage-Apprenti':'https://iili.io/dugPeBj.png',
    'Garage-Carrosier':'https://iili.io/dugPvrQ.png',
    'Garage-Client':'https://iili.io/dugPS2V.png',
    'Garage-Fournisseur d huile':'https://iili.io/dugPgkP.png',
    'Garage-Gerant':'https://iili.io/durFPwu.png',
    'Garage-Technicien en pneumatique':'https://iili.io/dugPiQa.png',
    'Garage-Vendeur automobile':'https://iili.io/dugPZ4R.png',
    'Hopital-Agent de maintenance':'https://iili.io/dugPbYN.png',
    'Hopital-Cardiologue':'https://iili.io/dugi9TX.png',
    'Hopital-Cuisinier':'https://iili.io/dugiHjn.png',
    'Hopital-Medecin chef':'https://iili.io/dugi2CG.png',
    'Hopital-Patient':'https://iili.io/dugiF44.png',
    'Hopital-Sage femme':'https://iili.io/dugiqa2.png',
    'Hopital-Urgentiste':'https://iili.io/dugiCy7.png',
    'Hotel-Agent d entretient':'https://iili.io/dugiTCb.png',
    'Hotel-Bagagiste':'https://iili.io/dugiuGj.png',
    'Hotel-Barman':'https://iili.io/dugiA6x.png',
    'Hotel-Client':'https://iili.io/dugi53Q.png',
    'Hotel-Cuisinier':'https://iili.io/dugi7aV.png',
    'Hotel-Directeur':'https://iili.io/dugiY8B.png',
    'Hotel-Receptionniste':'https://iili.io/dugixje.png',
    'Pacquebot-Capitaine':'https://iili.io/dugiayP.png',
    'Pacquebot-Naufrage seccouru':'https://iili.io/dugilu1.png',
    'Pacquebot-Passager clandestin':'https://iili.io/dugi0wF.png',
    'Pacquebot-Passager de 1ere classe':'https://iili.io/dugi1Zg.png',
    'Pacquebot-Passager de 2nd classe':'https://iili.io/dugiGna.png',
    'Pacquebot-Pecheur':'https://iili.io/dugiMMJ.png',
    'Pacquebot-Scientifique':'https://iili.io/dugiV6v.png',
    'Parc d attraction-Caissier':'https://iili.io/dugihap.png',
    'Parc d attraction-Cuisinier':'https://iili.io/dugij8N.png',
    'Parc d attraction-Mascotte':'https://iili.io/dugiN9I.png',
    'Parc d attraction-Operateur de manege':'https://iili.io/dugiewX.png',
    'Parc d attraction-Technicien de maintenance':'https://iili.io/dugi8ns.png',
    'Parc d attraction-Visiteur':'https://iili.io/dugiSMG.png',
    'Parc d attraction-nettoyage':'https://iili.io/dugiOut.png',
    'Plage-Animateur de club':'https://iili.io/dugiUPf.png',
    'Plage-Barman':'https://iili.io/dugirF4.png',
    'Plage-Moniteur de ski nautique':'https://iili.io/dugi6S2.png',
    'Plage-Plongeur':'https://iili.io/dugii9S.png',
    'Plage-Surfeur':'https://iili.io/dugisA7.png',
    'Plage-Touriste':'https://iili.io/dugiLN9.png',
    'Plage-Vendeur ambulant':'https://iili.io/dugiQte.png',
    'Poste de police-Inspecteur':'https://iili.io/dugitou.png',
    'Poste de police-Lieutenant':'https://iili.io/dugiDMb.png',
    'Poste de police-Medecin legiste':'https://iili.io/dugibPj.png',
    'Poste de police-Policier':'https://iili.io/dugipKx.png',
    'Poste de police-Prisonnier':'https://iili.io/dugiycQ.png',
    'Poste de police-Procureur':'https://iili.io/dugs9SV.png',
    'Poste de police-Secretaire':'https://iili.io/dugsJHB.png',
    'Restaurant-Barman':'https://iili.io/dugsdAP.png',
    'Restaurant-Chef':'https://iili.io/dugs3DF.png',
    'Restaurant-Client':'https://iili.io/dugsKog.png',
    'Restaurant-Critique culinaire':'https://iili.io/dugsfVa.png',
    'Restaurant-Livreur':'https://iili.io/dugsqiJ.png',
    'Restaurant-Serveur':'https://iili.io/dugsnlR.png',
    'Restaurant-Sommelier':'https://iili.io/dugsTNt.png',
    'Sous marin-Cuisinier':'https://iili.io/dugsuDX.png',
    'Sous marin-Mecanicien':'https://iili.io/dugs5Vs.png',
    'Sous marin-Meteorologiste':'https://iili.io/dugs7iG.png',
    'Sous marin-Navigateur':'https://iili.io/dugsaff.png',
    'Sous marin-Plongeur':'https://iili.io/dugscl4.png',
    'Sous marin-Soldat':'https://iili.io/dugs1J2.png',
    'Sous marin-Technicien':'https://iili.io/dugsERS.png',
    'Station Polaire-Biologiste':'https://iili.io/dugsGO7.png',
    'Station Polaire-Chef d expedition':'https://iili.io/dugsMb9.png',
    'Station Polaire-Electricien':'https://iili.io/dugsWxe.png',
    'Station Polaire-Plombier':'https://iili.io/dugshib.png',
    'Station Polaire-Scientifique':'https://iili.io/dugswfj.png',
    'Station Polaire-Technicien':'https://iili.io/dugsN0x.png',
    'Station Polaire-Veterinaire':'https://iili.io/dugskJV.png',
    'Station Spatiale-Astronaute':'https://iili.io/dugsv5B.png',
    'Station Spatiale-Astronome':'https://iili.io/dugs8OP.png',
    'Station Spatiale-Chef communication':'https://iili.io/dugsSb1.png',
    'Station Spatiale-Electricien':'https://iili.io/dugsrWg.png',
    'Station Spatiale-Pilote':'https://iili.io/dugs4sa.png',
    'Station Spatiale-Soudeur':'https://iili.io/dugsPqJ.png',
    'Station Spatiale-Technicien':'https://iili.io/dugsi0v.png',
    'Studio de cinema-Acteur':'https://iili.io/dugssgR.png',
    'Studio de cinema-Cascadeur':'https://iili.io/dugsQJp.png',
    'Studio de cinema-Chef decorateur':'https://iili.io/dugsZ5N.png',
    'Studio de cinema-Costumier':'https://iili.io/dugsteI.png',
    'Studio de cinema-Doublure':'https://iili.io/dugsmzX.png',
    'Studio de cinema-Producteur':'https://iili.io/dugspXn.png',
    'Studio de cinema-Realisateur':'https://iili.io/dugsyss.png',
    'Supermarche-Agent d entretient':'https://iili.io/dugLHqG.png',
    'Supermarche-Agent de securite':'https://iili.io/dugLJ1f.png',
    'Supermarche-Caissier':'https://iili.io/dugLdg4.png',
    'Supermarche-Client':'https://iili.io/dugL3dl.png',
    'Supermarche-Directeur':'https://iili.io/dugLF72.png',
    'Supermarche-Fournisseur':'https://iili.io/dugLKeS.png',
    'Supermarche-Voleur':'https://iili.io/dugLBI9.png',
    'Theatre-Accessoiriste':'https://iili.io/dugLCXe.png',
    'Theatre-Comedien':'https://iili.io/dugLnLu.png',
    'Theatre-Metteur en scene':'https://iili.io/dugLxqb.png',
    'Theatre-Responsable Lumieres':'https://iili.io/dugLIrx.png',
    'Theatre-Responsable Son':'https://iili.io/dugLudQ.png',
    'Theatre-Spectateur':'https://iili.io/dugLRkB.png',
    'Theatre-Technicien':'https://iili.io/dugL5mP.png',
    'Train-Agent de nettoyage':'https://iili.io/dugLYI1.png',
    'Train-Conducteur':'https://iili.io/dugLahF.png',
    'Train-Controlleur':'https://iili.io/dugLcLg.png',
    'Train-Passager de 1ere classe':'https://iili.io/dugL0Ba.png',
    'Train-Passager de 2nd classe':'https://iili.io/dugL1EJ.png',
    'Train-Technicien':'https://iili.io/dugLM2R.png',
    'Train-Voyageur sans ticket':'https://iili.io/dugLV7p.png',
    'Universite-Agent d entretient':'https://iili.io/dugLWkN.png',
    'Universite-Bibliothecaire':'https://iili.io/dugLXpI.png',
    'Universite-Chercheur':'https://iili.io/dugLwhX.png',
    'Universite-Directeur':'https://iili.io/dugLv4f.png',
    'Universite-Etudiant':'https://iili.io/dugLS24.png',
    'Universite-Infirmiere':'https://iili.io/dugLUYl.png',
    'Universite-Professeur':'https://iili.io/dugLgv2.png',
    'Zoo-Animateur':'https://iili.io/dugLrpS.png',
    'Zoo-Chef animalier':'https://iili.io/dugL6T7.png',
    'Zoo-Dompteur':'https://iili.io/dugLiQe.png',
    'Zoo-Fauconnier':'https://iili.io/dugLLCu.png',
    'Zoo-Soigneur':'https://iili.io/dugLQEb.png',
    'Zoo-Veterinaire':'https://iili.io/dugLZ4j.png',
    'Zoo-Visiteur':'https://iili.io/dugLD3x.png'
}

for lieu_role, lien in DicoLiensCartes.items():
    print(lieu_role, lien)
    response = requests.get(lien)
    image_bytes = response.content  # Les bytes de l'image

    # Connexion à la base de données SQLite
    conn = sqlite3.connect('cartesJoueursAgentTrouble.db')
    curseur = conn.cursor()

    # Insertion des données dans la table CartesAgentTrouble
    query = "INSERT INTO cartesPersos (Lieu_Role, ImageBytes) VALUES (?, ?)"
    curseur.execute(query, (lieu_role, image_bytes))

    # Validation de la transaction et fermeture de la connexion
    conn.commit()
    curseur.close()
    conn.close()