name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # déclenche le déploiement à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to Raspberry Pi and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_SSH_KEY }}
          script: |
            cd ~/docker-stack/gamehub  # adapte le chemin à ton dépôt sur le Pi
            git pull origin main
            cd ..
            docker restart gamehub